### PR TITLE
Update the OpenCL core API to 2.2

### LINKED ISSUE #2: OpenCL 2.x support
With the progress of dcompute coming along nicely I am now at the point where I can start testing OpenCL. To do so I need derelict-cl to be able to support OpenCL 2.x

If someone could point me in the direction of how to go about supporting 2.x in derelict that would be much appreciated.

### PR DESCRIPTION
**Pull request by thewilsonator**
I still have to update the loader to load the new symbols, so don't pull yet. This ought to be able to be done as generated code via reflection of `OpenCLFunc`.

If someone wants to cross check that i've got everything against https://github.com/thewilsonator/opencl-headers that would be appreciated.

I haven't done anything about extensions yet.

Fixes #2

### CODE REVIEW

**Comment by p0nce** [comment]
OK ping me when you need merge and new tag. I can't test your work, without OpenCL 2.0 device.

**Comment by thewilsonator** [comment]
Will do, I'm going to test it with DCompute to make sure that it works. I'll let you know when that happens (hopefully sometime soon).

**Comment by thewilsonator** [comment]
@p0nce Tested it now works.

**Comment by p0nce** [comment]
Has the accidental `.dub/version.json` been removed?

**Comment by thewilsonator** [comment]
Files changed:
* `source/derelict/opencl/cl.d`
* `source/derelict/opencl/constants.d`
* `source/derelict/opencl/functions.d`
* `source/derelict/opencl/types.d`

I don't think its there.

**Pull request merged**
